### ISSUE TITLE
Reading the mode when both i2c and serial are enabled causes ValueError of 113

### ISSUE THREAD

**Issue by andrewcrlucas** [sneakypete81/usb_iss#233]
* usb_iss version:  latest version installed with pip
* Python version: 3.8.4
* Operating System: Window 10

### Description

I issued the setup_i2c_serial() command
I issued the read_iss_mode() command

ValueError: 113 is not a valid Mode

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zbnc7q\AppData\Roaming\Python\Python38\site-packages\usb_iss\usb_iss.py", line 204, in read_iss_mode
    return defs.Mode(self._drv.read(3)[2])
  File "C:\Program Files\Python38\lib\enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "C:\Program Files\Python38\lib\enum.py", line 600, in __new__
    raise exc
  File "C:\Program Files\Python38\lib\enum.py", line 584, in __new__
    result = cls._missing_(value)
  File "C:\Program Files\Python38\lib\enum.py", line 613, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 113 is not a valid Mode

**Comment by sneakypete81** [comment]
Thanks for reporting this, it should now be fixed in v2.0.1.
